### ISSUE TITLE
Website Doesn't Work

### ISSUE THREAD

**Issue by virtual-valerie** [Cheyenne-Moutain-Computer-Science-Club/club-website#1]
[plugin:vite:css] Failed to load PostCSS config (searchPath: /home/runner/CMHS-CS-Club): [Failed to load PostCSS config] Failed to load PostCSS config (searchPath: /home/runner/CMHS-CS-Club): [ReferenceError] module is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '/home/runner/CMHS-CS-Club/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
ReferenceError: module is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '/home/runner/CMHS-CS-Club/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at file:///home/runner/CMHS-CS-Club/postcss.config.js:1:1
    at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
    at async importDefault (file:///home/runner/CMHS-CS-Club/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:25930:18)
    at async Object.search (file:///home/runner/CMHS-CS-Club/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:18367:38)
    at async resolvePostcssConfig (file:///home/runner/CMHS-CS-Club/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:42395:22)
    at async compileCSS (file:///home/runner/CMHS-CS-Club/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:42163:27)
    at async TransformContext.transform (file:///home/runner/CMHS-CS-Club/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:41786:55)
    at async Object.transform (file:///home/runner/CMHS-CS-Club/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:35284:30)
/home/runner/CMHS-CS-Club/src/App.css

**Comment by mehallhm** [comment]
No
